# Generated by Django 4.2.6 on 2023-11-28 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('problem_statement', models.TextField(blank=True, max_length=255, null=True)),
                ('problem_document', models.FileField(upload_to='static/pdf')),
                ('answer_document', models.FileField(upload_to='static/pdf/answer')),
                ('category', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='learning_hub.category')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
